# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Server CI Test

on:
  pull_request:
    branches: ['master']
    paths: ['apps/server/**']

permissions:
  contents: read

jobs:
  flake8_and_pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f apps/server/requirements.txt ]; then pip install -r apps/server/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run coverage with pytest
      env:
        MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}
        NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        MONGO_DB_DATABASE: test_database
      run: |
        coverage run --source=apps/server/src -m pytest
        coverage xml
